version: "3.9"
services:
  grounding:
    image: pathwaycommons/grounding-search:latest
    restart: unless-stopped
    container_name: grounding
    depends_on:
      - index
    ports:
      - "3000:3000"
    environment:
      ELASTICSEARCH_HOST: "index:9200"
      SWAGGER_HOST: "localhost:3000"
    networks:
      - grounding-search-network
    command: ["./wait-for-elasticsearch.sh", "index:9200", "npm", "run", "boot"]
  index:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    restart: unless-stopped
    container_name: index
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - in-data:/usr/share/elasticsearch/data
    networks:
      - grounding-search-network

volumes:
  in-data:

networks:
  grounding-search-network:
    driver: bridge
